import type { SupabaseClient } from '@supabase/supabase-js';

import { ApiError } from '../../middleware/api-error';
import type { BlockedCategory } from '../sessions/blocklist';

export interface VenueRecord {
  readonly id: string;
  // Nullable since Phase 7's account-deletion cascade (20260801000000):
  // owner_id is SET NULL, not CASCADEd, when its owning host deletes their
  // account — the venue (a shared B2B asset other users' sessions may
  // still reference) survives as an orphan rather than disappearing.
  readonly ownerId: string | null;
  readonly name: string;
  readonly addressLabel: string | null;
  // No expiry, unlike a session's qr_token (Phase 6 task 2 — a printed
  // venue code is meant to stay valid until deliberately regenerated).
  readonly qrToken: string;
  readonly qrTokenIssuedAt: string;
  readonly createdAt: string;
  // Phase 9 (plan §3): the ceiling on what a static_qr session at this
  // venue may block. Granted out of band by the owner flipping the column
  // in Supabase — the same manual-flag posture Verified Host itself uses
  // (ARCHITECTURE.md §10), and for the same reason: a venue session seats
  // up to 200 strangers, so "the business chooses" needs a check that isn't
  // the business.
  readonly approvedBlockedCategories: readonly BlockedCategory[];
  readonly approvedBlockedPackages: readonly string[];
}

export interface NewVenueInput {
  // Generated by create-venue.ts before insert (same reasoning as
  // create-session.ts generating its own id) — the qr_token embeds this id,
  // so Node must know it before the row exists.
  readonly id: string;
  readonly ownerId: string;
  readonly name: string;
  readonly addressLabel: string | null;
  readonly qrToken: string;
}

interface VenueRow {
  id: string;
  owner_id: string | null;
  name: string;
  address_label: string | null;
  qr_token: string;
  qr_token_issued_at: string;
  created_at: string;
  approved_blocked_categories: BlockedCategory[];
  approved_blocked_packages: string[];
}

const toVenueRecord = (row: VenueRow): VenueRecord => ({
  id: row.id,
  ownerId: row.owner_id,
  name: row.name,
  addressLabel: row.address_label,
  qrToken: row.qr_token,
  qrTokenIssuedAt: row.qr_token_issued_at,
  createdAt: row.created_at,
  approvedBlockedCategories: row.approved_blocked_categories,
  approvedBlockedPackages: row.approved_blocked_packages,
});

const VENUE_COLUMNS =
  'id, owner_id, name, address_label, qr_token, qr_token_issued_at, created_at, approved_blocked_categories, approved_blocked_packages';

// Thin persistence seam over public.venues, same shape as SessionsStore.
// getVenueById is the one method the sessions module depends on directly
// (create-session's ownership check, Phase 6 task 1) — kept on this store
// rather than duplicated so there is exactly one venue-reading code path.
export interface VenuesStore {
  createVenue(input: NewVenueInput): Promise<VenueRecord>;
  listVenuesForOwner(ownerId: string): Promise<readonly VenueRecord[]>;
  getVenueById(id: string): Promise<VenueRecord | null>;
  // Invalidates the venue's printed code by minting a fresh token —
  // always a deliberate, confirmed action (POST /venues/:id/qr/regenerate),
  // never automatic. Scoped to (id, ownerId) so one host can never
  // regenerate another's venue code even with a guessed id.
  regenerateQrToken(id: string, ownerId: string, qrToken: string): Promise<VenueRecord | null>;
}

export const createSupabaseVenuesStore = (client: SupabaseClient): VenuesStore => ({
  async createVenue(input) {
    const { data, error } = await client
      .from('venues')
      .insert({
        id: input.id,
        owner_id: input.ownerId,
        name: input.name,
        address_label: input.addressLabel,
        qr_token: input.qrToken,
      })
      .select(VENUE_COLUMNS)
      .single<VenueRow>();

    if (error !== null) {
      throw new ApiError(500, 'venue_create_failed', error.message);
    }
    return toVenueRecord(data);
  },

  async listVenuesForOwner(ownerId) {
    const { data, error } = await client
      .from('venues')
      .select(VENUE_COLUMNS)
      .eq('owner_id', ownerId)
      .order('created_at', { ascending: false });

    if (error !== null) {
      throw new ApiError(500, 'venue_list_failed', error.message);
    }
    return (data ?? []).map((row) => toVenueRecord(row as VenueRow));
  },

  async getVenueById(id) {
    const { data, error } = await client
      .from('venues')
      .select(VENUE_COLUMNS)
      .eq('id', id)
      .maybeSingle<VenueRow>();

    if (error !== null) {
      throw new ApiError(500, 'venue_lookup_failed', error.message);
    }
    return data === null ? null : toVenueRecord(data);
  },

  async regenerateQrToken(id, ownerId, qrToken) {
    const { data, error } = await client
      .from('venues')
      .update({ qr_token: qrToken, qr_token_issued_at: new Date().toISOString() })
      .eq('id', id)
      .eq('owner_id', ownerId)
      .select(VENUE_COLUMNS)
      .maybeSingle<VenueRow>();

    if (error !== null) {
      throw new ApiError(500, 'venue_qr_regenerate_failed', error.message);
    }
    return data === null ? null : toVenueRecord(data);
  },
});
